/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as RecurrenceRouteImport } from './routes/recurrence'
import { Route as InstallmentsRouteImport } from './routes/installments'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as ApiCronMaterializeRecurrenceRouteImport } from './routes/api/cron.materialize-recurrence'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const RecurrenceRoute = RecurrenceRouteImport.update({
  id: '/recurrence',
  path: '/recurrence',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallmentsRoute = InstallmentsRouteImport.update({
  id: '/installments',
  path: '/installments',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronMaterializeRecurrenceRoute =
  ApiCronMaterializeRecurrenceRouteImport.update({
    id: '/api/cron/materialize-recurrence',
    path: '/api/cron/materialize-recurrence',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/installments': typeof InstallmentsRoute
  '/recurrence': typeof RecurrenceRoute
  '/transactions': typeof TransactionsRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/api/cron/materialize-recurrence': typeof ApiCronMaterializeRecurrenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/installments': typeof InstallmentsRoute
  '/recurrence': typeof RecurrenceRoute
  '/transactions': typeof TransactionsRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/api/cron/materialize-recurrence': typeof ApiCronMaterializeRecurrenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/categories': typeof CategoriesRoute
  '/installments': typeof InstallmentsRoute
  '/recurrence': typeof RecurrenceRoute
  '/transactions': typeof TransactionsRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/api/cron/materialize-recurrence': typeof ApiCronMaterializeRecurrenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/categories'
    | '/installments'
    | '/recurrence'
    | '/transactions'
    | '/api/transactions'
    | '/api/cron/materialize-recurrence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/categories'
    | '/installments'
    | '/recurrence'
    | '/transactions'
    | '/api/transactions'
    | '/api/cron/materialize-recurrence'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/categories'
    | '/installments'
    | '/recurrence'
    | '/transactions'
    | '/api/transactions'
    | '/api/cron/materialize-recurrence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  CategoriesRoute: typeof CategoriesRoute
  InstallmentsRoute: typeof InstallmentsRoute
  RecurrenceRoute: typeof RecurrenceRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiTransactionsRoute: typeof ApiTransactionsRoute
  ApiCronMaterializeRecurrenceRoute: typeof ApiCronMaterializeRecurrenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recurrence': {
      id: '/recurrence'
      path: '/recurrence'
      fullPath: '/recurrence'
      preLoaderRoute: typeof RecurrenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installments': {
      id: '/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof InstallmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/materialize-recurrence': {
      id: '/api/cron/materialize-recurrence'
      path: '/api/cron/materialize-recurrence'
      fullPath: '/api/cron/materialize-recurrence'
      preLoaderRoute: typeof ApiCronMaterializeRecurrenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  CategoriesRoute: CategoriesRoute,
  InstallmentsRoute: InstallmentsRoute,
  RecurrenceRoute: RecurrenceRoute,
  TransactionsRoute: TransactionsRoute,
  ApiTransactionsRoute: ApiTransactionsRoute,
  ApiCronMaterializeRecurrenceRoute: ApiCronMaterializeRecurrenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
