/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiTransactionsRouteImport } from './routes/api/transactions'
import { Route as AuthedTransactionsRouteImport } from './routes/_authed/transactions'
import { Route as AuthedFaturasRouteImport } from './routes/_authed/faturas'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as ApiCronMaterializeRecurrenceRouteImport } from './routes/api/cron.materialize-recurrence'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedFaturasAccountIdRouteImport } from './routes/_authed/faturas_.$accountId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTransactionsRoute = ApiTransactionsRouteImport.update({
  id: '/api/transactions',
  path: '/api/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTransactionsRoute = AuthedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFaturasRoute = AuthedFaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiCronMaterializeRecurrenceRoute =
  ApiCronMaterializeRecurrenceRouteImport.update({
    id: '/api/cron/materialize-recurrence',
    path: '/api/cron/materialize-recurrence',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedFaturasAccountIdRoute = AuthedFaturasAccountIdRouteImport.update({
  id: '/faturas_/$accountId',
  path: '/faturas/$accountId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AuthedAccountsRoute
  '/faturas': typeof AuthedFaturasRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/faturas/$accountId': typeof AuthedFaturasAccountIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/materialize-recurrence': typeof ApiCronMaterializeRecurrenceRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/accounts': typeof AuthedAccountsRoute
  '/faturas': typeof AuthedFaturasRoute
  '/transactions': typeof AuthedTransactionsRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/': typeof AuthedIndexRoute
  '/faturas/$accountId': typeof AuthedFaturasAccountIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/materialize-recurrence': typeof ApiCronMaterializeRecurrenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/faturas': typeof AuthedFaturasRoute
  '/_authed/transactions': typeof AuthedTransactionsRoute
  '/api/transactions': typeof ApiTransactionsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/faturas_/$accountId': typeof AuthedFaturasAccountIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/materialize-recurrence': typeof ApiCronMaterializeRecurrenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/accounts'
    | '/faturas'
    | '/transactions'
    | '/api/transactions'
    | '/faturas/$accountId'
    | '/api/auth/$'
    | '/api/cron/materialize-recurrence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/accounts'
    | '/faturas'
    | '/transactions'
    | '/api/transactions'
    | '/'
    | '/faturas/$accountId'
    | '/api/auth/$'
    | '/api/cron/materialize-recurrence'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/accounts'
    | '/_authed/faturas'
    | '/_authed/transactions'
    | '/api/transactions'
    | '/_authed/'
    | '/_authed/faturas_/$accountId'
    | '/api/auth/$'
    | '/api/cron/materialize-recurrence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiTransactionsRoute: typeof ApiTransactionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronMaterializeRecurrenceRoute: typeof ApiCronMaterializeRecurrenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/transactions': {
      id: '/api/transactions'
      path: '/api/transactions'
      fullPath: '/api/transactions'
      preLoaderRoute: typeof ApiTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/transactions': {
      id: '/_authed/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthedTransactionsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/faturas': {
      id: '/_authed/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof AuthedFaturasRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/cron/materialize-recurrence': {
      id: '/api/cron/materialize-recurrence'
      path: '/api/cron/materialize-recurrence'
      fullPath: '/api/cron/materialize-recurrence'
      preLoaderRoute: typeof ApiCronMaterializeRecurrenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/faturas_/$accountId': {
      id: '/_authed/faturas_/$accountId'
      path: '/faturas/$accountId'
      fullPath: '/faturas/$accountId'
      preLoaderRoute: typeof AuthedFaturasAccountIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedFaturasRoute: typeof AuthedFaturasRoute
  AuthedTransactionsRoute: typeof AuthedTransactionsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedFaturasAccountIdRoute: typeof AuthedFaturasAccountIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedFaturasRoute: AuthedFaturasRoute,
  AuthedTransactionsRoute: AuthedTransactionsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedFaturasAccountIdRoute: AuthedFaturasAccountIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiTransactionsRoute: ApiTransactionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronMaterializeRecurrenceRoute: ApiCronMaterializeRecurrenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
